### ISSUE TITLE
Error on "localizedPlural" with correct arguments ("Localized value requires arguments"). v 1.0.3

### ISSUE THREAD

**Issue by zinukArtem** [steelkiwi/SKLocalizable#4]
in my func

> override func awakeFromNib() {
>         super.awakeFromNib()
>  ....
> commonUILabel.text = "locKey".localizedPlural(arguments: ["arg1": value])
> ...
> }

next in tread is `String+Localizable.swift` file with next function:

>     public func localizedPlural(tableName: String? = nil, arguments: CVarArg...) -> String {
>         return String.localizedStringWithFormat(self.localized(tableName: tableName), arguments)
>     }

by parameters  `tableName=nil`, `arguments=([String:String])` with correct value and key, and `self = locKey`.
this method call `localizedStringWithFormat`, but next in thread queue is `String+Localizable.swift` file and 

> public func localized(tableName: String? = nil, bundle: Bundle = .localization, arguments: Dictionary<String, Any>? = nil) -> String {
> ...

function. And in this func i don't have `arguments` values and get `assertionFailure("Localized value requires arguments")` error

**Comment by OlesenkoViktor** [comment]
**Invalid parameters format - you should use queue of params instead of dict**. Example: `"locKey".localizedPlural(arguments: value)`
Currently there is no support for named parameters and native way was used. 
If you have different order of parameters in different languages, as solution, you can put full localized text in format rule

**But in the same time error with passing arguments exist. Looking for solution**

SO question - https://stackoverflow.com/questions/54289157/passing-cvararg-in-inner-func

**Comment by OlesenkoViktor** [comment]
@zinukArtem you can use this commit in your dependency manager for now. This fix will be released in 1.0.4 version later
